In [ ]:
#Question 1
import numpy as np
a=np.array([(1,2,3),(3,4,3)])
a=a.tolist()
print(a)

[[1, 2, 3], [3, 4, 3]]


In [ ]:
#Question 2 
import numpy as np
country_elements=np.array([(1,2,3),(3,4,3),(2,3,4)])
Easily= np.trace(country_elements)
print(country_elements)
print(Easily)

[[1 2 3]
 [3 4 3]
 [2 3 4]]
9


In [4]:
#Question 3
import numpy as np
s=np.array([(1,2,3),(3,4,3),(2,3,4)])
print("Numbers greater than 3 ",s[s>3])

Numbers greater than 3  [4 4]


In [5]:
#Question 4
import numpy as np
s=np.array([(1,2,3),(3,4,3),(2,3,4)])
print(s)

[[1 2 3]
 [3 4 3]
 [2 3 4]]


In [6]:
#Question 5
import numpy as np
s=np.array([(1,2,3),(3,4,3),(5,8,9)])
y=s-s.mean( axis= 1 , keepdims = True)
print(y)

[[-1.          0.          1.        ]
 [-0.33333333  0.66666667 -0.33333333]
 [-2.33333333  0.66666667  1.66666667]]
